language: node_js
node_js:
  - "node"
before_script: npm run build
before_deploy: npm run prerelease
deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    upload_dir: public/js
    local_dir: release
    on:
      branch: release
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: $S3_HF_BUCKET
    skip_cleanup: true
    upload_dir: js
    local_dir: release
    on:
      branch: release
  - provider: npm
    email: "api@hellosign.com"
    api_key: $NPM_API_KEY
    skip_cleanup: true
    tag: next
    on:
      branch: master
  - provider: npm
    email: "api@hellosign.com"
    api_key: $NPM_API_KEY
    skip_cleanup: true
    tag: latest
    on:
      branch: release
