language: node_js
node_js:
  - "node"
before_script:
  - npm run build
deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    upload_dir: public/js/embedded/${TRAVIS_TAG}
    local_dir: umd
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta)\.[0-9]+)?$ # All releases.
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: umd/*
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ # Stable releases only.
  - provider: npm
    email: $NPM_EMAIL_ADDRESS
    api_key: $NPM_API_KEY
    skip_cleanup: true
    tag: latest
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ # Stable releases only.
  - provider: npm
    email: $NPM_EMAIL_ADDRESS
    api_key: $NPM_API_KEY
    skip_cleanup: true
    tag: next
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta)\.[0-9]+$ # Pre-releases only.
